### ISSUE TITLE
dbus-launch running from desktop

### ISSUE THREAD

**Issue by intika** [FadySGhatas/kde-dolphin-single-instance#2]
when starting from desktop it does not work but when starting from command line it does work

i found a solution tho... 

i have to run "dbus-launch dolphin %u" to open desktop folder then it works 
i managed to edit this settings on systemsettings5 > application > default application > file manager

**Comment by intika** [comment]
dolphin.desktop 
```
[Desktop Entry]
Comment[en_US]=
Comment=
Exec=dbus-launch dolphin %u
GenericName[en_US]=
GenericName=
Icon=org.kde.plasma.folder
MimeType=inode/directory;
Name[en_US]=dolphin
Name=dolphin
NoDisplay=true
Path=
StartupNotify=false
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=none
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by intika** [comment]
i have made some changes to your work have a look ;)
thanks for sharing your code ;)
https://github.com/intika/kde-dolphin-single-instance

**Comment by FadySGhatas** [comment]
@intika You're the best!
I really hope KDE merges this to dolphin's main codebase, it's a must have feature and after adding that as a selectable option, it's ready to be shipped.

**Comment by intika** [comment]
No, you are the best ! you made my additional features possible, without your work i would not had the time to do the whole thing
